### ISSUE TITLE
Android7.0 上面有问题  定位权限没有 申请权限点击后卡死

### ISSUE THREAD

**Issue by DreamPWJ** [DaiHuaXieHuaKai/GaoDeLocation#1]
Android7.0 上面有问题  定位权限没有 申请权限点击后卡死

**Comment by ghost** [comment]
安卓7.0  无法进行请求定位权限

**Comment by DreamPWJ** [comment]
重新申请权限 在代码写 判断没有权限重新申请

**Comment by DaiHuaXieHuaKai** [comment]
@shx1545 @DreamPWJ   这个插件当时的初衷是学习怎么自己写插件，所以没有考虑到权限问题，现在已经加上了，但是由于身边没有android7.0的机子，所以暂时不知道有没有什么问题，你们可以先试试。

**Comment by DreamPWJ** [comment]
非常好 再封装个导航的话 也用你的 谢谢了

**Comment by CuiShiKang** [comment]
这个不是安卓7.0版本的问题，你这个获取权限的方法回掉 onRequestPermissionsResult 打错了，应该是onRequestPermissionResult 你的Permission后面多了一个s，导致获取权限之后方法不能回掉。亲测，有效。 @DaiHuaXieHuaKai

**Comment by DaiHuaXieHuaKai** [comment]
@CuiShiKang 谢谢指出，因为之前没有写获取权限的代码，后面加上去了也没有测试过。
