### ISSUE TITLE
定位信息获取

### ISSUE THREAD

**Issue by xucoolmeng** [DaiHuaXieHuaKai/GaoDeLocation#2]
请问定位数据如何通过回调获取呢  GaoDe.getCurrentPosition(successCallback, failedCallback);

**Comment by xucoolmeng** [comment]
按照你的写法重新写了中国移动的地图定位，但是拿不到回调的数据

**Comment by DaiHuaXieHuaKai** [comment]
@xucoolmeng 你要调试你的插件代码啊。successCallback就是一个回调方法。

**Comment by xucoolmeng** [comment]
已解决 thank
